name: Validate with Hacs

on:
  push:
    branches:
      - master

  pull_request:
    branches: '*'

  schedule:
    - cron: "0 0 * * *"

jobs:
  validate_hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
